version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: autocompany
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - WORKERS=2
      - PORT=8000
      - PYTHONUNBUFFERED=1
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py makemigrations autocompany && python manage.py migrate autocompany && uwsgi --http :8000 --processes 2 --module autocompany.wsgi:application"

volumes:
  postgres_data:
