# Generated by Django 5.0 on 2024-02-08 15:42

import autocompany.modules.shared.enum.AddressType
import autocompany.modules.shared.enum.ProductCategory
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'autocompany.app_users',
            },
        ),
        migrations.CreateModel(
            name='AppUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(default='guest_user', max_length=50)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
            options={
                'db_table': 'autocompany.app_user_roles',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('postal_code', models.TextField(max_length=10)),
                ('street_address', models.TextField()),
                ('address_type', models.CharField(default='shipping', verbose_name=autocompany.modules.shared.enum.AddressType.AddressType)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='autocompany.appuser')),
            ],
            options={
                'db_table': 'autocompany.addresses',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_user_permissions', to='autocompany.appuserrole'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='autocompany.appuser')),
            ],
            options={
                'db_table': 'autocompany.carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='initialized', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_address', to='autocompany.address')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='autocompany.appuser')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='autocompany.cart')),
            ],
            options={
                'db_table': 'autocompany.orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(default=autocompany.modules.shared.enum.ProductCategory.ProductCategory['OTHER'], max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocompany.appuser')),
            ],
            options={
                'db_table': 'autocompany.products',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_user', to='autocompany.appuser')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='autocompany.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_product', to='autocompany.product')),
            ],
            options={
                'db_table': 'autocompany.cart_items',
            },
        ),
    ]
