# Generated by Django 5.0 on 2024-02-08 12:08

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(default='guest_user', max_length=50)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
            options={
                'db_table': 'autocompany.app_user_roles',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user_permissions', to='autocompany.appuserrole')),
            ],
            options={
                'db_table': 'autocompany.app_users',
            },
        ),
    ]
