# Generated by Django 5.0 on 2024-02-08 12:21

import autocompany.modules.shared.enum.ProductCategory
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(default=autocompany.modules.shared.enum.ProductCategory.ProductCategory['OTHER'], max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocompany.appuser')),
            ],
            options={
                'db_table': 'autocompany.products',
            },
        ),
    ]
