# Generated by Django 5.0 on 2024-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('autocompany', '0002_enrich_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
