# Generated by Django 5.0 on 2024-02-08 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0005_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='initialized', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_address', to='autocompany.address')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='autocompany.appuser')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='autocompany.cart')),
            ],
            options={
                'db_table': 'autocompany.orders',
            },
        ),
    ]
